server:
  port: 9014
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: langchain4j-14chat-mcp

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${aliQwen-api-key}
        model-name: qwen-plus
      chat-model:
        api-key: ${aliQwen-api-key}
        model-name: qwen-plus

# ?????????debug????????? langchain ?????????
logging:
  level:
    dev:
      langchain4j: DEBUG